architect:
  - Andrew-Sem
docker:
  image: yegor256/rultor-image:1.13.0
merge:
  script: |
    cargo --color=never test -vv
    cargo --color=never fmt --check
    cargo doc --no-deps
    cargo clippy